# Site settings
title:Dominic's Resume
#description: "A progmatic programmer"
#baseurl:        "/tale"
url:            "http://resume.dominic.pro"

# Author
author:
  name:         Dominic
  url:          http://resume.dominic.pro
  email:        dominic0312@126.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
